---
# This playbook will install common dependencies


- name: Install common package
  yum: name={{ item }} state=installed
  with_items:
    - wget
    - vim
    - git
    - nginx
    - libselinux-python

- include: update_epel.yml

- name: Mkdir install directory
  command: mkdir -p /data/shell