---
# This playbook will install common dependencies

# - include_tasks: update_resolv.yml

- include_tasks: update_CentOS-Base.repo.yml

- name: Install common package
  yum: name={{ item }} state=installed
  with_items:
    - wget
    - vim
    - git
    # - nginx
    - xz
    - mlocate
    - libselinux-python

# 安装这个依赖之后 安装php扩展才会生成configure
- name: Install autoconf
  yum: name={{ item }} state=installed
  with_items:
    - m4
    - autoconf

- name: Install autoconf
  yum: name={{ item }} state=installed
  with_items:
    - svn

- name: updatedb
  command: updatedb


- name: create install directory
  file: path={{ install_dir }} state=directory owner=root group=root mode=0766


-include_tasks: sync_time.yml
# - include_tasks: upgrade_gcc.yml
- include_tasks: update_CentOS-Base.repo.yml