---
# This playbook will install proxychains

- name: enable devtoolset-3
  command: scl enable devtoolset-3 bash

- name: Copy the code from repository
  git: repo={{ proxychains_repository }} dest={{ proxychains_dir }} accept_hostkey=yes

- name: Install proxychains
  command: chdir={{ proxychains_dir }} {{ item }}
  with_items:
    - ./configure
    - make
    - make install

- name: Copy conf
  command: cp {{ proxychains_dir }}/src/proxychains.conf /etc/proxychains.conf

- name: Config env
  command: "{{ item }}"
  with_items: 
    - sed -i 's/socks4..127.0.0.1 9050/socks5 {{ shadowsocks_ip }} {{ shadowsocks_port}}/g' /etc/proxychains.conf