---
# This playbook will install node.js

- name: Download Node.js 
  get_url:
    url: https://nodejs.org/dist/v6.11.0/node-v6.11.0.tar.gz
    dest: "{{ install_dir }}/node-v6.11.0.tar.gz

- name: Extract anchive
  unarchive:
    dest: "{{ install_dir }}"
    src: "{{ install_dir }}/node-v6.11.0.tar.gz"
    creates: "{{ install_dir }}/node-v6.11.0
    copy: no


## need upgrade gcc to 4.8+ first, then do it. if not will show error, below.
- name: enable devtoolset-3
  command: scl enable devtoolset-3 bash

- name: Install node.js
  command: chdir={{ install_dir }}/node-v6.11.0 {{ item }}
  with_items:
    - ./configure
    - make
    - make install

- name: cnpm instead of npm
  command: npm install -g cnpm --registry=https://registry.npm.taobao.org