--- 
# This playbook will install pip

# need to install common laybook 

- name: Install depend package
  yum: name={{ item }} state=installed
  with_items:
    - ncurses-devel

- name: Create Erlang Install Directory
  file: path={{ erlang_dir }} state=directory owner=root group=root mode=0766

- name: Download Node.js 
  get_url:
    url: "{{ erlang_url }}"
    dest: "{{ erlang_dir }}/otp_src_19.0.tar.gz"

# - name: Copy Otp Package
#   copy: src=otp_src_19.0.tar.gz dest="{{ erlang_dir }}/otp_src_19.0.tar.gz"

- name: Extract Archive
  unarchive:
    dest: "{{ erlang_dir }}"
    src: "{{ erlang_dir }}/otp_src_19.0.tar.gz"
    creates: "{{ erlang_dir }}/otp_src_19.0"
    copy: no

- name: Install Erlang
  command: chdir={{ erlang_dir }}/otp_src_19.0 {{ item }}
  with_items:
    - ./configure
    - make
    - make install
