---
# This playbook will install laravel-angular-admin
# step by step to run below in china. there may be error.

# - name: Copy the code from repository
#   git: repo={{ laravel_angular_admin_repository }} dest={{ laravel_angular_admin_dir }} accept_hostkey=yes

# - name: Config mysql data
#   command: mysql -uroot -e "create database order_food default character set utf8";
#   ignore_errors: yes

# - name: Config need to tool
#   command: chdir={{ laravel_angular_admin_dir }} {{ item }}
#   with_items:
#     - cnpm install bower
#     - cnpm install gulp

# - name: Config composer dependencies for laravel-angular-admin
#   command: chdir={{ laravel_angular_admin_dir }} {{ item }}
#   with_items:
#     - composer install

# - name: Config cnpm dependencies for laravel-angular-admin
#   command: chdir={{ laravel_angular_admin_dir }} {{ item }}
#   with_items:
#     - cnpm install
#   ignore_errors: yes

# - name: Config bower dependencies for laravel-angular-admin
#   command: "{{ laravel_angular_admin_dir }}/node_modules/bower/bin/bower install {{ laravel_angular_admin_dir }}/bower.json --allow-root"
#   register: result
#   until: result == 0
#   retries: 10
#   delay: 2
#   ignore_errors: yes

# - name: Config env
#   command: chdir={{ laravel_angular_admin_dir }} {{ item }}
#   with_items:
#     - sed -i 's/DB_DATABASE=homestead/DB_DATABASE=order_food/g' .env
#     - sed -i 's/DB_USERNAME=homestead/DB_USERNAME=root/g' .env
#     - sed -i 's/DB_PASSWORD=secret/DB_PASSWORD=/g' .env

# - name: create and fill database
#   command: chdir={{ laravel_angular_admin_dir }} {{ item }}
#   with_items:
#     - php artisan migrate
#     - php artisan db:seed

# - name: gulp
#   command: chdir={{ laravel_angular_admin_dir }} {{ item }}
#   with_items:
#     - ./node_modules/gulp/bin/gulp.js

# - name: gulp
#   command: chdir={{ laravel_angular_admin_dir }} {{ item }}
#   with_items:
#     - chmod -R 777 public
#     - chmod -R 777 storage

- name: start web service
  command: php {{ laravel_angular_admin_dir }}/artisan serve --host=192.168.0.99 &