---
# This playbook will install pip

- name: start epel
  yum: name={{ item }} state=installed
  with_items:
    - epel-release
    - python-pip

- name: upgrade pip
  command: pip install -- upgrade pip