---
# This playbook will upgrade autoconf to 2.69

- name: Download Autoconf2.69
  get_url:
    url: http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
    dest: "{{ install_dir }}/autoconf-2.69.tar.gz"

- name: Extract Anchive
  unarchive:
    dest: "{{ install_dir }}"
    src: "{{ install_dir }}/autoconf-2.69.tar.gz"
    creates: "{{ install_dir }}/autoconf-2.69"
    copy: no

- name: Install Autoconf2.69
  command: chdir={{ install_dir }}/autoconf-2.69 {{ item }}
  with_items:
    - ./configure --prefix=/usr
    - make
    - make install