---
# This playbook will install php dependencies

- name: Install php
  yum: name={{ item }} state=installed
  with_items:
    - gcc
    - gcc-c++
    - make
    - zlib
    - zlib-devel
    - pcre
    - pcre-devel
    - libjpeg
    - libjpeg-devel
    - libpng
    - libpng-devel
    - freetype
    - freetype-devel
    - libxml2
    - libxml2-devel
    - glibc
    - glibc-devel
    - glib2
    - glib2-devel
    - bzip2
    - bzip2-devel
    - ncurses
    - ncurses-devel
    - curl
    - curl-devel
    - e2fsprogs
    - e2fsprogs-devel
    - krb5-devel
    - openssl
    - openssl-devel
    - openldap
    - openldap-devel
    - openldap-clients
    - openldap-servers

- name: Copy php install shell
  template: src=php.shell.j2 dest=/data/shell/php_install.sh

- name: Copy tar.gz
  copy: src=libmcrypt-2.5.7.tar.gz dest=/data/shell

- name: Extract archive
  unarchive:
    dest: /data/shell
    src: /data/shell/libmcrypt-2.5.7.tar.gz
    creates: /data/shell/libmcrypt-2.5.7
    copy: no

- name: Install libmcrypt
  command: chdir=/data/shell/libmcrypt-2.5.7 {{ item }}
  with_items:
    - ./configure
    - make
    - make install

- name: Run php install
  command: sh /data/shell/php_install.sh