---
# This playbook deploys env

- name: deploy common
  hosts: servers
  remote_user: root

  roles:
    - common

  tags:
    - common

- name: deploy work environment
  hosts: servers
  remote_user: root

  roles:
    - work

  tags:
    - work