---
# This playbook deploys env

- name: deploy common
  hosts: vimservers
  remote_user: root

  roles:
    - common

  tags:
    - common

- name: deploy vim
  hosts: vimservers
  remote_user: root

  roles:
    - vim

  tags:
    - vim